# Generated by Django 4.2 on 2023-07-01 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='query',
            field=models.CharField(default=datetime.datetime(2023, 7, 1, 7, 28, 49, 487383, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
    ]
