# Generated by Django 4.2 on 2023-07-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0007_alter_favorite_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
